export interface Article {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  categories: string[];
  image: string;
  slug: string;
  author: {
    name: string;
    avatar: string;
    email: string;
  };
  date: string;
  readTime: string;
  featured?: boolean;
}

const defaultAuthor = {
  name: "The Recap Report",
  avatar: "https://therecapreport.com/wp-content/uploads/2021/11/favicon.png",
  email: "info@therecapreport.com",
};

export const articles: Article[] = [
  {
    id: "1",
    title: "More Than a Network: How Angel Livas Is Building Space, Power, and Ownership for Black Creators",
    excerpt: "There are moments in culture when someone quietly builds the kind of infrastructure that changes everything — not overnight, not loudly, but steadily, intentionally, and with purpose rooted in community.",
    category: "Business",
    categories: ["Business", "Entertainment", "Featured", "Trending"],
    image: "https://therecapreport.com/wp-content/uploads/yootheme/cache/03/Angel-Livas-at-ALIVE-Studios-032d05a7.jpg",
    slug: "angel-livas-building-space-power-ownership",
    author: defaultAuthor,
    date: "March 15, 2026",
    readTime: "8 min read",
    featured: true,
  },
  {
    id: "2",
    title: "Nine Losses, Two Brain Surgeries, One Mission: Rachell Dumas Is Changing How Women Are Heard in Healthcare",
    excerpt: "A powerful story of resilience, advocacy, and the fight for women's health equity in a system that often fails to listen.",
    category: "Health & Beauty",
    categories: ["Health and Beauty", "Business", "Lifestyle"],
    image: "https://therecapreport.com/wp-content/uploads/2026/02/RachellDumas3.webp",
    slug: "rachell-dumas-changing-women-healthcare",
    author: defaultAuthor,
    date: "February 19, 2026",
    readTime: "6 min read",
  },
  {
    id: "3",
    title: "\"They Didn't Listen\": Why So Many Black Patients Leave the Doctor Feeling Dismissed",
    excerpt: "An investigation into systemic healthcare bias and the voices demanding change in how Black patients are treated.",
    category: "Health & Beauty",
    categories: ["Education", "Health and Beauty", "Influential People", "Lifestyle"],
    image: "https://therecapreport.com/wp-content/uploads/2026/02/IMG_6771.jpeg",
    slug: "black-patients-feeling-dismissed",
    author: defaultAuthor,
    date: "February 10, 2026",
    readTime: "7 min read",
  },
  {
    id: "4",
    title: "Aaliyah Duah Is Making Financial Literacy Fun — And Gen Z Is Finally Listening",
    excerpt: "At just 22, Aaliyah Duah is turning complex financial concepts into engaging content that resonates with an entire generation.",
    category: "Business",
    categories: ["Business", "Education", "Entertainment"],
    image: "https://therecapreport.com/wp-content/uploads/yootheme/cache/a7/1677797533591-a752c5f0.jpg",
    slug: "aaliyah-duah-financial-literacy-gen-z",
    author: defaultAuthor,
    date: "March 8, 2026",
    readTime: "5 min read",
  },
  {
    id: "5",
    title: "Beyond the Spin: Kayla Tucker Adams on Power, Purpose, and Telling the Truth in Public Relations",
    excerpt: "A candid conversation about navigating power, purpose, and authenticity in the world of public relations.",
    category: "Business",
    categories: ["Business", "Education", "Entertainment", "Influential People"],
    image: "https://therecapreport.com/wp-content/uploads/yootheme/cache/36/kayla-t-adams-36012740.webp",
    slug: "kayla-tucker-adams-public-relations",
    author: defaultAuthor,
    date: "March 5, 2026",
    readTime: "6 min read",
  },
  {
    id: "6",
    title: "Inside the World of Mychel \"Snoop\" Dillard: Healing, Hustle & Snooping 4 Love",
    excerpt: "From healing to hustle, Mychel Dillard opens up about building an empire rooted in love, resilience, and authenticity.",
    category: "Entertainment",
    categories: ["Business", "Entertainment", "Lifestyle"],
    image: "https://therecapreport.com/wp-content/uploads/2025/11/0C81BEF1-1A41-4C6F-9E3B-83EF19F5865B.jpeg",
    slug: "mychel-snoop-dillard-healing-hustle",
    author: defaultAuthor,
    date: "November 4, 2025",
    readTime: "7 min read",
  },
  {
    id: "7",
    title: "From Classroom to Kitchen: How Vanetta Roy Built Atlanta's Beloved \"Eat My Biscuits\"",
    excerpt: "The inspiring story of a teacher-turned-entrepreneur who created one of Atlanta's most beloved food brands.",
    category: "Food",
    categories: ["Business", "Food", "Influential People"],
    image: "https://therecapreport.com/wp-content/uploads/yootheme/cache/64/IMG_0076-64707877.jpeg",
    slug: "vanetta-roy-eat-my-biscuits",
    author: defaultAuthor,
    date: "February 28, 2026",
    readTime: "5 min read",
  },
  {
    id: "8",
    title: "Thomas Ricks, #14: From SWAC All-American, to SWAT, to CEO of Executive Protection",
    excerpt: "A remarkable journey from the football field to law enforcement to building a premier executive protection company.",
    category: "Sports",
    categories: ["Business", "Education", "Entertainment", "Sports"],
    image: "https://therecapreport.com/wp-content/uploads/yootheme/cache/77/Bricks-Solo-IMG_7585-1-77435e80.jpeg",
    slug: "thomas-ricks-swac-swat-ceo",
    author: defaultAuthor,
    date: "February 25, 2026",
    readTime: "8 min read",
  },
  {
    id: "9",
    title: "Black Maternal Health Is Not Genetics. It's Bias, Delayed Care, and a System That Doesn't Listen",
    excerpt: "Dr. Eboni January explains what must change to address the maternal health crisis affecting Black women across America.",
    category: "Health & Beauty",
    categories: ["Business", "Health and Beauty"],
    image: "https://therecapreport.com/wp-content/uploads/2025/12/Screenshot-2025-12-18-at-10.51.02-AM.png",
    slug: "black-maternal-health-bias-delayed-care",
    author: defaultAuthor,
    date: "December 18, 2025",
    readTime: "9 min read",
  },
  // ── NEW articles from live site ──
  {
    id: "10",
    title: "Be Bold, Be Bright: Derek Amarillas' Debut Book \"Socko\" Teaches Kids the Power of Showing Up as Themselves",
    excerpt: "From boardrooms to bookstores, Derek Amarillas is redefining what it means to take risks and live boldly with a heartwarming children's picture book that celebrates individuality and resilience.",
    category: "Education",
    categories: ["Education", "Health and Beauty", "Lifestyle"],
    image: "https://therecapreport.com/wp-content/uploads/2025/08/Derek-Amarillas-Headshot-w-Book.png",
    slug: "derek-amarillas-socko-book",
    author: defaultAuthor,
    date: "August 7, 2025",
    readTime: "5 min read",
  },
  {
    id: "11",
    title: "From Lab to Legacy: How Dr. Isfahan is Redefining Black Hair Care Through Science",
    excerpt: "A biomedical scientist turned entrepreneur is creating science-backed hair care products that address the unique needs of Black women — rooted in real research, not marketing hype.",
    category: "Health & Beauty",
    categories: ["Health and Beauty", "Business", "Lifestyle"],
    image: "https://therecapreport.com/wp-content/uploads/2025/08/IMG_9637-e1754248102893.png",
    slug: "dr-isfahan-black-hair-care-science",
    author: defaultAuthor,
    date: "August 3, 2025",
    readTime: "6 min read",
  },
  {
    id: "12",
    title: "Wrapped in Rest: How The Rest Spot Holds Space for Black Women to Heal",
    excerpt: "In a world where burnout is normalized, The Rest Spot in Smyrna, Georgia is a radical act of softness — a sanctuary where Black and Brown women are encouraged to slow down and simply rest.",
    category: "Lifestyle",
    categories: ["Lifestyle", "Health and Beauty", "Business"],
    image: "https://therecapreport.com/wp-content/uploads/2025/08/IMG_0068.jpeg",
    slug: "the-rest-spot-black-women-heal",
    author: defaultAuthor,
    date: "August 3, 2025",
    readTime: "5 min read",
  },
  {
    id: "13",
    title: "A New Chapter of Advocacy: LaToya Dwight's Fight for Fibroid Awareness",
    excerpt: "A businesswoman, wife, mother, and survivor turned advocate, LaToya Dwight has emerged as a bold voice in the fight for menstrual equity and reproductive health awareness.",
    category: "Health & Beauty",
    categories: ["Health and Beauty", "Influential People", "Business"],
    image: "https://therecapreport.com/wp-content/uploads/2025/07/Fibroid-scaled.png",
    slug: "latoya-dwight-fibroid-awareness",
    author: defaultAuthor,
    date: "July 11, 2025",
    readTime: "7 min read",
  },
  {
    id: "14",
    title: "The Biggest Family Reunion in Illinois: Mike Page's Love Revolution",
    excerpt: "While success often leads people away from their roots, music industry entrepreneur Mike Page chose a different path — investing his time, money, and passion back into his hometown through the 'Love on the Lawn' festival.",
    category: "Lifestyle",
    categories: ["Lifestyle", "Entertainment", "Influential People"],
    image: "https://therecapreport.com/wp-content/uploads/2025/08/IMG_1609.jpeg",
    slug: "mike-page-love-revolution",
    author: defaultAuthor,
    date: "August 14, 2025",
    readTime: "6 min read",
  },
  {
    id: "15",
    title: "Detroit's Tel K. Ganesan vs. Everybody: Indian-American Engineer Turned Filmmaker Leading a Stellar Black Cast in Trap City",
    excerpt: "With a background in engineering and entrepreneurship, Tel K. Ganesan made a bold pivot into storytelling — today streaming on Prime Video and Apple TV, sparking conversations around ambition and identity.",
    category: "Entertainment",
    categories: ["Entertainment", "Lifestyle", "Business"],
    image: "https://therecapreport.com/wp-content/uploads/2025/05/trap_city.jpg",
    slug: "tel-ganesan-trap-city",
    author: defaultAuthor,
    date: "May 2, 2025",
    readTime: "7 min read",
  },
  {
    id: "16",
    title: "Healing the Whole Woman: Dr. Jennifer Mbianda's Vision for Transformative, Culturally Rooted Care",
    excerpt: "In a world that often asks women to carry it all while caring for themselves last, Dr. Jennifer Mbianda is creating a safe, intentional space where women are seen, affirmed, and given the tools to heal wholly.",
    category: "Health & Beauty",
    categories: ["Health and Beauty", "Lifestyle", "Influential People"],
    image: "https://therecapreport.com/wp-content/uploads/2025/05/Dr-Mbianda-FAcebook-Blazer-Seated-465819505_17957967749837290_8414043212908819847_n.jpg",
    slug: "dr-jennifer-mbianda-culturally-rooted-care",
    author: defaultAuthor,
    date: "May 2, 2025",
    readTime: "6 min read",
  },
  {
    id: "17",
    title: "The Power of Us: Vanessa Bouie and Her Family's Blueprint for Success",
    excerpt: "When the Bouie family gathered around the kitchen table during uncertain times, they didn't just share a meal — they shared a dream that would become a blueprint for building something beautiful together.",
    category: "Lifestyle",
    categories: ["Lifestyle", "Health and Beauty", "Business"],
    image: "https://therecapreport.com/wp-content/uploads/2025/05/Screenshot-2025-05-09-at-8.36.21%E2%80%AFAM.png",
    slug: "vanessa-bouie-family-blueprint",
    author: defaultAuthor,
    date: "May 9, 2025",
    readTime: "5 min read",
  },
  {
    id: "18",
    title: "Dr. Tanika Long: Building Bridges of Hope in Barnesville and Beyond",
    excerpt: "Sometimes all it takes is one moment to change everything. For Dr. Tanika Long, that moment came during the height of the pandemic — and it led her to build bridges of hope in her hometown.",
    category: "Health & Beauty",
    categories: ["Health and Beauty", "Education", "Influential People"],
    image: "https://therecapreport.com/wp-content/uploads/2025/05/WhatsApp-Image-2025-05-12-at-21.54.23_0f100f8c.jpg",
    slug: "dr-tanika-long-barnesville",
    author: defaultAuthor,
    date: "May 13, 2025",
    readTime: "6 min read",
  },
];

export const trendingHeadlines = [
  "Angel Livas Is Building Space & Ownership for Black Creators",
  "Rachell Dumas Is Changing How Women Are Heard in Healthcare",
  "Why So Many Black Patients Leave the Doctor Feeling Dismissed",
  "Aaliyah Duah Is Making Financial Literacy Fun for Gen Z",
  "Kayla Tucker Adams on Power & Truth in Public Relations",
  "Vanetta Roy Built Atlanta's Beloved 'Eat My Biscuits'",
  "Thomas Ricks: From SWAC All-American to CEO",
  "Dr. Isfahan Is Redefining Black Hair Care Through Science",
  "The Rest Spot Holds Space for Black Women to Heal",
];

export const categories = [
  "Entertainment",
  "Lifestyle",
  "Business",
  "Health & Beauty",
  "Top 10",
  "Education",
  "Sports",
  "Food",
];
